# The URL the site will be built for
base_url = "https://panevain.github.io/CS5744_TransitFlow/"
compile_sass = true
build_search_index = false
theme = "book"
title = "CS 5744 Project 1"

[markdown]
highlight_code = true
highlight_theme = "solarized-light"

[extra]
# Put all your custom variables here
